name: Build and Deploy (CRA → GitHub Pages)

on:
  push:
    branches: [ main ]      # deploys current branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (CRA)
        run: npm run build

      # If you prefer to ensure the domain from CI instead of Pages settings,
      # create a repo variable CUSTOM_DOMAIN and uncomment:
      # - name: Write CNAME
      #   run: echo "${{ vars.CUSTOM_DOMAIN }}" > build/CNAME

      # SPA fallback so client-side routes work on refresh
      - name: SPA 404 fallback
        run: cp build/index.html build/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
